// src/data/cropData.js

export const cropData = [
  {
    id: 1,
    name: 'Rice',
    scientificName: 'Oryza sativa',
    briefDescription: 'A staple food crop cultivated widely in India, primarily during the Kharif season. It requires hot and humid climate with abundant water.',
    fullDescription: 'Rice is the most important food crop of India and is grown in diverse agro-climatic conditions. It is a semi-aquatic plant and needs high temperatures (above 25°C) and high humidity (above 75%) along with ample rainfall (100 cm to 200 cm) or irrigation. It is cultivated in almost all states, with major producers being West Bengal, Uttar Pradesh, Punjab, and Andhra Pradesh.',
    image: 'https://images.unsplash.com/photo-1592997572594-34be01bc36c7?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    climate: 'Hot and humid (25°C - 35°C, 75%+ humidity)',
    soil: 'Alluvial soils, clayey soils, loam soils with good water retention capacity.',
    sowingTime: 'Kharif (June-July), sometimes Zaid/Rabi in certain regions.',
    harvestingTime: 'Kharif (October-November), depending on variety and sowing.',
    waterRequirements: 'High, standing water is ideal for most varieties. Requires 100-200 cm rainfall.',
    commonPests: 'Stem Borer, Leaf Folder, Brown Plant Hopper, Rice Hispa.',
    commonDiseases: 'Blast, Bacterial Blight, Sheath Blight, Tungro Virus.',
    yield: 'Average 2.5-3.5 tons/hectare for traditional varieties; 5-7 tons/hectare for high-yielding varieties.',
    cultivationPractices: [
      'Nursery preparation and transplanting (or Direct Seeded Rice).',
      'Puddling and leveling of fields.',
      'Application of basal fertilizers (N, P, K).',
      'Water management: maintaining standing water.',
      'Weed control through manual weeding or herbicides.',
      'Integrated Pest and Disease Management (IPM).',
      'Harvesting when grains are mature, followed by threshing and drying.'
    ],
    fertilizerManagement: 'Typically requires 120-150 kg Nitrogen, 60 kg Phosphorus, 40 kg Potassium per hectare, adjusted based on soil test results. Nitrogen applied in splits.',
    marketInfo: 'Key staple, good demand. MSP (Minimum Support Price) provided by government. Market prices fluctuate based on supply and quality.'
  },
  {
    id: 2,
    name: 'Wheat',
    scientificName: 'Triticum aestivum',
    briefDescription: 'A major Rabi crop, known for its extensive cultivation in the northern plains of India. It thrives in cool, dry conditions.',
    fullDescription: 'Wheat is the second most important food crop of India, primarily grown in the Rabi season. It requires a cool growing season and bright sunshine at the time of ripening. Ideal temperature range is 10-15°C for germination and 21-26°C for ripening. Annual rainfall of 50-75 cm is ideal, evenly distributed over the growing season. Major wheat-producing states are Uttar Pradesh, Punjab, Haryana, and Madhya Pradesh.',
    image: 'https://images.unsplash.com/photo-1529511582893-2d7e684dd128?q=80&w=1033&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
    climate: 'Cool growing season (10-15°C), bright sunshine at ripening (21-26°C).',
    soil: 'Well-drained fertile loamy and clayey loamy soils. Black soils are also suitable.',
    sowingTime: 'Rabi (October-December)',
    harvestingTime: 'Rabi (March-April)',
    waterRequirements: 'Moderate, 3-5 irrigations depending on rainfall.',
    commonPests: 'Aphids, Termites, Armyworm.',
    commonDiseases: 'Rusts (Yellow, Brown, Black), Loose Smut, Powdery Mildew, Karnal Bunt.',
    yield: 'Average 3-4.5 tons/hectare; 5-6 tons/hectare for irrigated high-yielding varieties.',
    cultivationPractices: [
      'Thorough land preparation (ploughing, leveling).',
      'Timely sowing is crucial for good yield.',
      'Application of balanced fertilizers.',
      'Critical irrigations at crown root initiation, tillering, flowering, grain filling stages.',
      'Weed control (broadleaf and grassy weeds).',
      'Pest and disease monitoring and management.',
      'Harvesting when grains are hard and dry.'
    ],
    fertilizerManagement: 'Typically 120 kg Nitrogen, 60 kg Phosphorus, 40 kg Potassium per hectare, with Zinc sulfate application in deficient soils.',
    marketInfo: 'Crucial for food security. Strong government procurement at MSP. Market prices are generally stable due to high demand.'
  },
  {
  id: 3,
  name: 'Barley',
  scientificName: 'Hordeum vulgare',
  briefDescription: 'A Rabi cereal crop grown in cooler climates, used for food, fodder, and brewing.',
  fullDescription: 'Barley is a hardy cereal crop cultivated mainly in the Rabi season. It thrives in dry, cool climates and is grown in states like Rajasthan, Uttar Pradesh, Madhya Pradesh, and Haryana. It is used for human consumption, animal feed, and in the malting and brewing industries.',
  image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Barley_%28Hordeum_vulgare%29_-_United_States_National_Arboretum_-_24_May_2009.jpg/1280px-Barley_%28Hordeum_vulgare%29_-_United_States_National_Arboretum_-_24_May_2009.jpg',
  climate: 'Cool and dry (15°C - 25°C)',
  soil: 'Well-drained loamy to sandy loam soils with moderate fertility.',
  sowingTime: 'Rabi (October-November)',
  harvestingTime: 'Rabi (March-April)',
  waterRequirements: 'Low to moderate, drought-tolerant.',
  commonPests: 'Aphids, Armyworms, Cutworms.',
  commonDiseases: 'Leaf Rust, Powdery Mildew, Smuts.',
  yield: '2.5-3.5 tons/hectare under good management.',
  cultivationPractices: [
    'Timely sowing with certified seeds.',
    'Proper seed rate and spacing.',
    'Balanced fertilization and weed control.',
    'Irrigation at critical stages like tillering and grain filling.',
    'Timely harvesting to avoid grain shattering.'
  ],
  fertilizerManagement: '60-80 kg Nitrogen, 40 kg Phosphorus per hectare. Apply nitrogen in two splits.',
  marketInfo: 'Used in food, feed, and brewing. Prices vary with demand from malt and beer industries.'
},

{
  id: 4,
  name: 'Sorghum (Jowar)',
  scientificName: 'Sorghum bicolor',
  briefDescription: 'A drought-resistant cereal crop grown in semi-arid regions, used for food, fodder, and biofuel.',
  fullDescription: 'Jowar is a staple food grain in many parts of India, especially in Maharashtra, Karnataka, and Madhya Pradesh. It is highly drought-tolerant and suitable for rainfed farming. It is used in traditional flatbreads and as livestock feed.',
  image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Sorghum_bicolor03.jpg/800px-Sorghum_bicolor03.jpg',
  climate: 'Warm and dry (25°C - 32°C), drought-tolerant.',
  soil: 'Well-drained loamy to sandy loam soils.',
  sowingTime: 'Kharif (June-July), Rabi (October-November in some regions).',
  harvestingTime: 'Kharif (September-October), Rabi (February-March).',
  waterRequirements: 'Low to moderate, suitable for rainfed areas.',
  commonPests: 'Shoot Fly, Stem Borer, Midge.',
  commonDiseases: 'Anthracnose, Rust, Downy Mildew.',
  yield: '2-3 tons/hectare; higher with hybrids.',
  cultivationPractices: [
    'Timely sowing with certified seeds.',
    'Thinning and gap filling.',
    'Weed control and pest monitoring.',
    'Balanced fertilization and irrigation (if needed).',
    'Harvesting at grain maturity.'
  ],
  fertilizerManagement: '80-100 kg Nitrogen, 40 kg Phosphorus per hectare.',
  marketInfo: 'Used in traditional foods and fodder. Demand rising for gluten-free diets.'
},
{
  id: 5,
  name: 'Finger Millet (Ragi)',
  scientificName: 'Eleusine coracana',
  briefDescription: 'A highly nutritious millet rich in calcium and iron, grown in hilly and dry regions.',
  fullDescription: 'Ragi is a resilient millet crop grown in Karnataka, Tamil Nadu, Odisha, and Uttarakhand. It is known for its high nutritional value and is used in porridge, rotis, and health foods. It thrives in poor soils and low rainfall areas.',
  image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Ragi_Plant.jpg/1024px-Ragi_Plant.jpg',
  climate: 'Cool and dry (20°C - 30°C), drought-tolerant.',
  soil: 'Red loamy, lateritic, or sandy soils with good drainage.',
  sowingTime: 'Kharif (June-July), Rabi (October-November in some areas).',
  harvestingTime: 'Kharif (October-November), Rabi (January-February).',
  waterRequirements: 'Low, suitable for dryland farming.',
  commonPests: 'Stem Borer, Aphids, Cutworms.',
  commonDiseases: 'Blast, Leaf Spot, Rust.',
  yield: '1.5-2.5 tons/hectare; higher with improved varieties.',
  cultivationPractices: [
    'Direct sowing or transplanting.',
    'Timely weeding and thinning.',
    'Use of organic and chemical fertilizers.',
    'Pest and disease monitoring.',
    'Harvesting when ear heads turn brown.'
  ],
  fertilizerManagement: '60-80 kg Nitrogen, 40 kg Phosphorus per hectare.',
  marketInfo: 'High demand in health food markets. Promoted under millet missions.'
},
{
  id: 6,
  name: 'Oats',
  scientificName: 'Avena sativa',
  briefDescription: 'A cool-season cereal crop grown for grain and fodder, valued for its health benefits.',
  fullDescription: 'Oats are a Rabi season crop grown in cooler regions of India, especially in Punjab, Haryana, and Uttar Pradesh. They are used for human consumption (as oatmeal and breakfast cereals) and as green fodder for livestock. Oats are rich in dietary fiber and beta-glucan, making them a popular health food.',
  image: 'https://forcesofnaturemedicine.com/cdn/shop/articles/Homeopathic-Ingredient-Avena-Sativa-Oats.jpg?v=1706731807&width=1070',
  climate: 'Cool and moist (15°C - 25°C), frost-tolerant.',
  soil: 'Well-drained loamy soils with good organic content.',
  sowingTime: 'Rabi (October-November)',
  harvestingTime: 'Rabi (March-April)',
  waterRequirements: 'Moderate, 2-3 irrigations depending on rainfall.',
  commonPests: 'Aphids, Armyworms, Cutworms.',
  commonDiseases: 'Rust, Smut, Leaf Blight.',
  yield: '2.5-4 tons/hectare for grain; higher for fodder varieties.',
  cultivationPractices: [
    'Timely sowing with certified seeds.',
    'Proper spacing and seed rate.',
    'Balanced fertilization and weed control.',
    'Irrigation at tillering and grain filling stages.',
    'Harvesting when grains are firm and dry.'
  ],
  fertilizerManagement: '60-80 kg Nitrogen, 40 kg Phosphorus per hectare. Apply nitrogen in two splits.',
  marketInfo: 'Growing demand in health food and livestock feed sectors. Prices influenced by processing industry.'
},
{
  id: 7,
  name: 'Gram (Chana)',
  scientificName: 'Cicer arietinum',
  briefDescription: 'A major Rabi pulse crop grown in dry regions, rich in protein and widely consumed in India.',
  fullDescription: 'Gram, also known as chickpea or chana, is the most important pulse crop in India. It is grown mainly in the Rabi season in states like Madhya Pradesh, Uttar Pradesh, Rajasthan, and Maharashtra. It is a key source of protein in vegetarian diets and is used in various forms—whole, split, or flour.',
  image: 'https://www.agrifarming.in/wp-content/uploads/Guide-to-Chickpea-Bengal-GramChana-Farming-2.jpg',
  climate: 'Cool and dry (20°C - 25°C), sensitive to frost.',
  soil: 'Well-drained loamy soils with neutral pH.',
  sowingTime: 'Rabi (October-November)',
  harvestingTime: 'Rabi (February-March)',
  waterRequirements: 'Low, drought-tolerant. Requires 1-2 irrigations.',
  commonPests: 'Pod Borer, Cutworm, Aphids.',
  commonDiseases: 'Fusarium Wilt, Ascochyta Blight, Rust.',
  yield: '1.2-2 tons/hectare; higher with improved varieties.',
  cultivationPractices: [
    'Deep ploughing and seedbed preparation.',
    'Timely sowing with treated seeds.',
    'Weed control and light irrigation.',
    'Use of resistant varieties.',
    'Harvesting when pods turn brown and dry.'
  ],
  fertilizerManagement: '20-30 kg Nitrogen, 40-60 kg Phosphorus per hectare. Rhizobium inoculation recommended.',
  marketInfo: 'High domestic demand. Prices influenced by production and government procurement.'
},
{
  id: 8,
  name: 'Lentil (Masoor)',
  scientificName: 'Lens culinaris',
  briefDescription: 'A protein-rich Rabi pulse crop grown in cooler climates, used in dals and soups.',
  fullDescription: 'Lentil is a widely grown pulse crop in India, especially in Uttar Pradesh, Madhya Pradesh, Bihar, and West Bengal. It is a short-duration crop that fits well in crop rotations. Lentils are rich in protein and iron and are a staple in Indian diets.',
  image: 'https://villagevasi.com/wp-content/uploads/2021/11/WhatsApp-Image-2021-11-19-at-1.27.11-AM.jpeg',
  climate: 'Cool and dry (18°C - 25°C), frost-sensitive.',
  soil: 'Loamy to clay loam soils with good drainage.',
  sowingTime: 'Rabi (October-November)',
  harvestingTime: 'Rabi (February-March)',
  waterRequirements: 'Low, 1-2 irrigations if rainfall is insufficient.',
  commonPests: 'Aphids, Cutworms, Pod Borers.',
  commonDiseases: 'Rust, Wilt, Collar Rot.',
  yield: '1-1.5 tons/hectare; higher with improved practices.',
  cultivationPractices: [
    'Timely sowing with certified seeds.',
    'Proper spacing and seed rate.',
    'Weed control and light irrigation.',
    'Use of disease-resistant varieties.',
    'Harvesting when pods are dry and brittle.'
  ],
  fertilizerManagement: '20-25 kg Nitrogen, 40-50 kg Phosphorus per hectare. Rhizobium inoculation improves yield.',
  marketInfo: 'Steady demand in domestic markets. Prices vary with production and imports.'
},
{
  id: 9,
  name: 'Pigeon Pea (Arhar/Tur)',
  scientificName: 'Cajanus cajan',
  briefDescription: 'A major Kharif pulse crop known for its deep roots and drought resistance, widely used in Indian cuisine.',
  fullDescription: 'Pigeon pea, also known as Arhar or Tur, is a key pulse crop grown during the Kharif season. It is a deep-rooted legume that improves soil fertility and is widely consumed across India in the form of dal. Major producing states include Maharashtra, Madhya Pradesh, Karnataka, and Uttar Pradesh.',
  image: 'https://vajiramandravi.com/current-affairs/wp-content/uploads/2025/04/pigeon_pea.webp',
  climate: 'Warm and semi-arid (25°C - 35°C), drought-tolerant.',
  soil: 'Well-drained loamy to black cotton soils.',
  sowingTime: 'Kharif (June-July)',
  harvestingTime: 'Kharif (December-January)',
  waterRequirements: 'Low to moderate, suitable for rainfed areas.',
  commonPests: 'Pod Borer, Leaf Hopper, Aphids.',
  commonDiseases: 'Wilt, Sterility Mosaic Disease, Leaf Spot.',
  yield: '1-2 tons/hectare; higher with improved varieties.',
  cultivationPractices: [
    'Deep ploughing and timely sowing.',
    'Use of resistant varieties.',
    'Weed control and light irrigation if needed.',
    'Intercropping with cereals or oilseeds.',
    'Harvesting when pods are dry and brown.'
  ],
  fertilizerManagement: '20-30 kg Nitrogen, 40-60 kg Phosphorus per hectare. Rhizobium inoculation recommended.',
  marketInfo: 'High demand for dal. Prices influenced by monsoon and government procurement.'
},
{
  id: 10,
  name: 'Green Gram (Moong)',
  scientificName: 'Vigna radiata',
  briefDescription: 'A short-duration pulse crop grown in all three seasons, valued for its protein-rich seeds and soil-enriching properties.',
  fullDescription: 'Green gram, or Moong, is a versatile pulse crop grown in Kharif, Rabi, and Zaid seasons. It matures quickly and is often used in crop rotations. It is rich in protein and easy to digest, making it a staple in Indian diets. Major producers include Rajasthan, Maharashtra, Andhra Pradesh, and Karnataka.',
  image: 'https://as1.ftcdn.net/jpg/04/37/05/18/1000_F_437051870_bChAJqNGI2Jzpc00WvQZASx5WNv6Ms1o.jpg',
  climate: 'Warm and dry (25°C - 35°C), sensitive to waterlogging.',
  soil: 'Well-drained sandy loam to loamy soils.',
  sowingTime: 'Kharif (June-July), Rabi (October-November), Zaid (March-April)',
  harvestingTime: '60-70 days after sowing, depending on season.',
  waterRequirements: 'Low, 1-2 irrigations if rainfall is insufficient.',
  commonPests: 'Whitefly, Thrips, Pod Borer.',
  commonDiseases: 'Yellow Mosaic Virus, Powdery Mildew, Leaf Spot.',
  yield: '0.8-1.2 tons/hectare; higher with improved practices.',
  cultivationPractices: [
    'Timely sowing with treated seeds.',
    'Weed control and pest monitoring.',
    'Use of short-duration, disease-resistant varieties.',
    'Harvesting when 80% pods are mature and dry.'
  ],
  fertilizerManagement: '20 kg Nitrogen, 40 kg Phosphorus per hectare. Rhizobium inoculation enhances yield.',
  marketInfo: 'Strong demand in health-conscious markets. Prices vary with seasonal supply.'
},
{
  id: 11,
  name: 'Black Gram (Urad)',
  scientificName: 'Vigna mungo',
  briefDescription: 'A protein-rich pulse crop grown in all three seasons, widely used in Indian cuisine and soil enrichment.',
  fullDescription: 'Black gram, or Urad, is a short-duration pulse crop cultivated during Kharif, Rabi, and Zaid seasons. It is a nitrogen-fixing legume that improves soil health and is used in dals, idli/dosa batter, and papads. Major producers include Madhya Pradesh, Uttar Pradesh, Andhra Pradesh, and Tamil Nadu.',
  image: 'https://tiimg.tistatic.com/fp/1/006/615/premium-and-organic-black-gram-895.jpg',
  climate: 'Warm and humid (25°C - 35°C), sensitive to waterlogging.',
  soil: 'Well-drained loamy to clay loam soils.',
  sowingTime: 'Kharif (June-July), Rabi (October-November), Zaid (March-April)',
  harvestingTime: '60-80 days after sowing, depending on season.',
  waterRequirements: 'Low, 1-2 irrigations if rainfall is insufficient.',
  commonPests: 'Whitefly, Aphids, Pod Borer.',
  commonDiseases: 'Yellow Mosaic Virus, Leaf Spot, Powdery Mildew.',
  yield: '0.8-1.2 tons/hectare; higher with improved practices.',
  cultivationPractices: [
    'Timely sowing with treated seeds.',
    'Weed control and pest monitoring.',
    'Use of short-duration, disease-resistant varieties.',
    'Harvesting when 80% pods are mature and dry.'
  ],
  fertilizerManagement: '20 kg Nitrogen, 40 kg Phosphorus per hectare. Rhizobium inoculation enhances yield.',
  marketInfo: 'High demand in culinary and processed food industries. Prices vary with seasonal supply.'
},
{
  id: 12,
  name: 'Mustard',
  scientificName: 'Brassica juncea',
  briefDescription: 'A major Rabi oilseed crop grown for its seeds, which are used for oil extraction and condiments.',
  fullDescription: 'Mustard is a cool-season oilseed crop widely cultivated in northern and central India. It is grown primarily for its oil-rich seeds and is also used as a spice. Major producing states include Rajasthan, Uttar Pradesh, Madhya Pradesh, and Haryana.',
  image: 'https://upload.wikimedia.org/wikipedia/commons/f/ff/Mustard_plant_flower.jpg',
  climate: 'Cool and dry (10°C - 25°C), frost-sensitive.',
  soil: 'Well-drained loamy to clay loam soils with good fertility.',
  sowingTime: 'Rabi (October-November)',
  harvestingTime: 'Rabi (February-March)',
  waterRequirements: 'Low to moderate, 2-3 irrigations depending on rainfall.',
  commonPests: 'Aphids, Painted Bug, Mustard Sawfly.',
  commonDiseases: 'White Rust, Alternaria Blight, Downy Mildew.',
  yield: '1.2-2 tons/hectare; higher with hybrids and good practices.',
  cultivationPractices: [
    'Timely sowing with certified seeds.',
    'Balanced fertilization and weed control.',
    'Irrigation at flowering and pod formation stages.',
    'Pest and disease monitoring.',
    'Harvesting when pods turn yellow and dry.'
  ],
  fertilizerManagement: '60-80 kg Nitrogen, 40 kg Phosphorus, 20 kg Potassium per hectare.',
  marketInfo: 'High demand for edible oil and condiments. MSP declared by government.'
},
{
  id: 13,
  name: 'Groundnut (Peanut)',
  scientificName: 'Arachis hypogaea',
  briefDescription: 'A Kharif oilseed crop grown for its edible seeds and oil, also used as fodder and in confectionery.',
  fullDescription: 'Groundnut is a leguminous oilseed crop grown mainly during the Kharif season in states like Gujarat, Andhra Pradesh, Tamil Nadu, and Karnataka. It is valued for its oil content and protein-rich seeds. It also improves soil fertility through nitrogen fixation.',
  image: 'https://via.placeholder.com/400x300/F4A460/000000?text=Groundnut+Crop',
  climate: 'Warm and moist (25°C - 35°C), sensitive to frost and waterlogging.',
  soil: 'Well-drained sandy loam to loamy soils with neutral pH.',
  sowingTime: 'Kharif (June-July), Rabi (October-November in southern India)',
  harvestingTime: 'Kharif (October-November), Rabi (February-March)',
  waterRequirements: 'Moderate, critical at flowering and pod development stages.',
  commonPests: 'Leaf Miner, Aphids, White Grub.',
  commonDiseases: 'Tikka Leaf Spot, Rust, Collar Rot.',
  yield: '1.5-2.5 tons/hectare; higher with improved varieties.',
  cultivationPractices: [
    'Seed treatment and timely sowing.',
    'Earthing up and weed control.',
    'Irrigation at pegging and pod filling stages.',
    'Use of resistant varieties.',
    'Harvesting when leaves yellow and pods mature.'
  ],
  fertilizerManagement: '20 kg Nitrogen, 40-60 kg Phosphorus, 40 kg Potassium per hectare. Gypsum application improves pod development.',
  marketInfo: 'Used in edible oil, snacks, and exports. Prices influenced by global oilseed markets.'
},
{
  id: 14,
  name: 'Soybean',
  scientificName: 'Glycine max',
  briefDescription: 'A high-protein oilseed crop grown mainly in the Kharif season, used for oil extraction and animal feed.',
  fullDescription: 'Soybean is a major Kharif oilseed crop cultivated in central India, especially in Madhya Pradesh, Maharashtra, and Rajasthan. It is rich in protein and oil and is used in food products, animal feed, and industrial applications. It also improves soil fertility through nitrogen fixation.',
  image: 'https://via.placeholder.com/400x300/FFA500/000000?text=Soybean+Crop',
  climate: 'Warm and moist (25°C - 30°C), requires well-distributed rainfall.',
  soil: 'Well-drained loamy to clay loam soils with good organic matter.',
  sowingTime: 'Kharif (June-July)',
  harvestingTime: 'Kharif (October-November)',
  waterRequirements: 'Moderate, critical at flowering and pod filling stages.',
  commonPests: 'Stem Fly, Girdle Beetle, Whitefly.',
  commonDiseases: 'Rust, Yellow Mosaic Virus, Anthracnose.',
  yield: '1.5-2.5 tons/hectare; higher with improved varieties.',
  cultivationPractices: [
    'Timely sowing with treated seeds.',
    'Weed control and pest monitoring.',
    'Balanced fertilization and irrigation if needed.',
    'Use of disease-resistant varieties.',
    'Harvesting when pods are dry and brown.'
  ],
  fertilizerManagement: '20-30 kg Nitrogen, 60-80 kg Phosphorus, 40 kg Potassium per hectare. Rhizobium inoculation enhances yield.',
  marketInfo: 'High demand in oil and feed industries. Prices influenced by global soybean markets.'
},
{
  id: 15,
  name: 'Sunflower',
  scientificName: 'Helianthus annuus',
  briefDescription: 'An oilseed crop grown in all seasons, known for its bright yellow flowers and high-quality edible oil.',
  fullDescription: 'Sunflower is a versatile oilseed crop grown in Kharif, Rabi, and Zaid seasons. It is cultivated in Karnataka, Maharashtra, Andhra Pradesh, and Tamil Nadu. The seeds are rich in oil and used for cooking oil, snacks, and industrial purposes.',
  image: 'https://via.placeholder.com/400x300/FFD700/000000?text=Sunflower+Crop',
  climate: 'Warm and sunny (20°C - 30°C), requires clear skies during flowering.',
  soil: 'Well-drained loamy soils with good fertility and neutral pH.',
  sowingTime: 'Kharif (June-July), Rabi (October-November), Zaid (February-March)',
  harvestingTime: '90-100 days after sowing, depending on season.',
  waterRequirements: 'Moderate, critical at flowering and seed filling stages.',
  commonPests: 'Helicoverpa, Whitefly, Leaf Hopper.',
  commonDiseases: 'Alternaria Blight, Rust, Downy Mildew.',
  yield: '1.2-2 tons/hectare; higher with hybrids.',
  cultivationPractices: [
    'Timely sowing with certified seeds.',
    'Weed control and balanced fertilization.',
    'Irrigation at critical growth stages.',
    'Pest and disease monitoring.',
    'Harvesting when flower heads turn brown and seeds are firm.'
  ],
  fertilizerManagement: '60-80 kg Nitrogen, 40-60 kg Phosphorus, 40 kg Potassium per hectare.',
  marketInfo: 'Used in edible oil and snack industries. Prices influenced by oil demand and imports.'
},
{
  id: 16,
  name: 'Soybean',
  scientificName: 'Glycine max',
  briefDescription: 'A protein-rich oilseed crop grown mainly in the Kharif season, used for oil extraction and animal feed.',
  fullDescription: 'Soybean is a major Kharif oilseed crop cultivated in Madhya Pradesh, Maharashtra, and Rajasthan. It is valued for its high protein and oil content and is used in food products, animal feed, and industrial applications. It also improves soil fertility through nitrogen fixation.',
  image: 'https://via.placeholder.com/400x300/DAA520/000000?text=Soybean+Crop',
  climate: 'Warm and moist (25°C - 30°C), requires well-distributed rainfall.',
  soil: 'Well-drained loamy to clay loam soils with good organic matter.',
  sowingTime: 'Kharif (June-July)',
  harvestingTime: 'Kharif (October-November)',
  waterRequirements: 'Moderate, critical at flowering and pod filling stages.',
  commonPests: 'Stem Fly, Girdle Beetle, Whitefly.',
  commonDiseases: 'Rust, Yellow Mosaic Virus, Anthracnose.',
  yield: '1.5-2.5 tons/hectare; higher with improved varieties.',
  cultivationPractices: [
    'Timely sowing with treated seeds.',
    'Weed control and pest monitoring.',
    'Balanced fertilization and irrigation if needed.',
    'Use of disease-resistant varieties.',
    'Harvesting when pods are dry and yellow.'
  ],
  fertilizerManagement: '20-30 kg Nitrogen, 60 kg Phosphorus, 40 kg Potassium per hectare. Rhizobium inoculation enhances yield.',
  marketInfo: 'High demand in oil and feed industries. Prices influenced by global soy markets.'
},
{
  id: 17,
  name: 'Sunflower',
  scientificName: 'Helianthus annuus',
  briefDescription: 'An oilseed crop grown in multiple seasons, known for its high-quality edible oil and attractive yellow flowers.',
  fullDescription: 'Sunflower is a fast-growing oilseed crop cultivated in Kharif, Rabi, and Zaid seasons. It is grown in Karnataka, Maharashtra, Andhra Pradesh, and Tamil Nadu. The seeds are rich in oil and used in cooking, cosmetics, and industrial products.',
  image: 'https://via.placeholder.com/400x300/FFD700/000000?text=Sunflower+Crop',
  climate: 'Warm and sunny (20°C - 30°C), sensitive to frost and waterlogging.',
  soil: 'Well-drained loamy soils with good fertility and neutral pH.',
  sowingTime: 'Kharif (June-July), Rabi (October-November), Zaid (February-March)',
  harvestingTime: '80-100 days after sowing, depending on variety.',
  waterRequirements: 'Moderate, 3-4 irrigations depending on season.',
  commonPests: 'Helicoverpa, Cutworms, Leaf Hoppers.',
  commonDiseases: 'Alternaria Blight, Rust, Downy Mildew.',
  yield: '1.2-2 tons/hectare; higher with hybrids.',
  cultivationPractices: [
    'Timely sowing with certified seeds.',
    'Weed control and pest monitoring.',
    'Balanced fertilization and irrigation.',
    'Harvesting when back of flower heads turn yellow and seeds are firm.'
  ],
  fertilizerManagement: '60-80 kg Nitrogen, 40 kg Phosphorus, 40 kg Potassium per hectare.',
  marketInfo: 'Used in edible oil and cosmetic industries. Prices influenced by oil demand and imports.'
},
{
  id: 18,
  name: 'Sesame (Til)',
  scientificName: 'Sesamum indicum',
  briefDescription: 'An ancient oilseed crop grown for its small, oil-rich seeds, used in cooking and traditional medicine.',
  fullDescription: 'Sesame is a drought-tolerant oilseed crop grown in Kharif and Rabi seasons. It is cultivated in Gujarat, West Bengal, Rajasthan, and Uttar Pradesh. The seeds are used for oil extraction and in sweets, snacks, and Ayurvedic preparations.',
  image: 'https://via.placeholder.com/400x300/F5DEB3/000000?text=Sesame+Crop',
  climate: 'Warm and dry (25°C - 35°C), drought-tolerant.',
  soil: 'Well-drained sandy loam to loamy soils with neutral pH.',
  sowingTime: 'Kharif (June-July), Rabi (October-November)',
  harvestingTime: 'Kharif (September-October), Rabi (January-February)',
  waterRequirements: 'Low, suitable for rainfed areas.',
  commonPests: 'Leaf Roller, Gall Fly, Whitefly.',
  commonDiseases: 'Leaf Spot, Phyllody, Powdery Mildew.',
  yield: '0.5-1.2 tons/hectare; higher with improved varieties.',
  cultivationPractices: [
    'Timely sowing with treated seeds.',
    'Weed control and thinning.',
    'Use of short-duration, disease-resistant varieties.',
    'Harvesting when capsules turn yellow and begin to split.'
  ],
  fertilizerManagement: '30-40 kg Nitrogen, 20 kg Phosphorus per hectare.',
  marketInfo: 'Used in oil, sweets, and exports. Prices influenced by festive demand and global markets.'
},
{
  id: 19,
  name: 'Linseed (Flaxseed)',
  scientificName: 'Linum usitatissimum',
  briefDescription: 'A Rabi oilseed crop grown for its seeds, which are rich in omega-3 fatty acids and used in food and industry.',
  fullDescription: 'Linseed is a cool-season oilseed crop cultivated mainly in Madhya Pradesh, Uttar Pradesh, Chhattisgarh, and Bihar. It is used for oil extraction, health supplements, and industrial applications like linoleum and paint.',
  image: 'https://via.placeholder.com/400x300/8B4513/FFFFFF?text=Linseed+Crop',
  climate: 'Cool and dry (15°C - 25°C), frost-sensitive.',
  soil: 'Well-drained loamy to clay loam soils.',
  sowingTime: 'Rabi (October-November)',
  harvestingTime: 'Rabi (February-March)',
  waterRequirements: 'Low to moderate, 2-3 irrigations depending on rainfall.',
  commonPests: 'Aphids, Cutworms, Flea Beetles.',
  commonDiseases: 'Rust, Wilt, Powdery Mildew.',
  yield: '0.8-1.5 tons/hectare; higher with improved practices.',
  cultivationPractices: [
    'Timely sowing with certified seeds.',
    'Weed control and pest monitoring.',
    'Balanced fertilization and irrigation.',
    'Harvesting when capsules turn brown and dry.'
  ],
  fertilizerManagement: '40-60 kg Nitrogen, 30-40 kg Phosphorus per hectare.',
  marketInfo: 'Rising demand in health food and industrial sectors. Prices influenced by global flaxseed markets.'
},
{
  id: 20,
  name: 'Castor',
  scientificName: 'Ricinus communis',
  briefDescription: 'An industrial oilseed crop grown for castor oil, used in lubricants, cosmetics, and pharmaceuticals.',
  fullDescription: 'Castor is a hardy oilseed crop cultivated mainly in Gujarat, Andhra Pradesh, and Rajasthan. It is grown for its seeds, which yield castor oil—a valuable industrial oil used in lubricants, paints, cosmetics, and medicines. The plant is drought-tolerant and thrives in semi-arid regions.',
  image: 'https://via.placeholder.com/400x300/708090/FFFFFF?text=Castor+Crop',
  climate: 'Warm and dry (20°C - 35°C), drought-tolerant.',
  soil: 'Well-drained sandy loam to loamy soils with neutral to slightly alkaline pH.',
  sowingTime: 'Kharif (July-August), Rabi (October-November in southern India)',
  harvestingTime: 'Kharif (December-January), Rabi (March-April)',
  waterRequirements: 'Low to moderate, 2-3 irrigations depending on rainfall.',
  commonPests: 'Castor Semilooper, Capsule Borer, Whitefly.',
  commonDiseases: 'Wilt, Leaf Spot, Powdery Mildew.',
  yield: '1-2 tons/hectare; higher with hybrids and good practices.',
  cultivationPractices: [
    'Timely sowing with certified seeds.',
    'Weed control and pest monitoring.',
    'Balanced fertilization and irrigation if needed.',
    'Harvesting when capsules dry and split open.'
  ],
  fertilizerManagement: '60-80 kg Nitrogen, 40 kg Phosphorus, 40 kg Potassium per hectare.',
  marketInfo: 'High demand in industrial sectors. India is a leading exporter of castor oil.'
},
{
  id: 21,
  name: 'Tobacco',
  scientificName: 'Nicotiana tabacum',
  briefDescription: 'A commercial crop grown for its leaves, used in the manufacture of cigarettes, cigars, and chewing tobacco.',
  fullDescription: 'Tobacco is a high-value cash crop cultivated in Andhra Pradesh, Karnataka, Gujarat, and Uttar Pradesh. It is grown primarily for its leaves, which are processed and used in various tobacco products. India is one of the largest producers and exporters of tobacco in the world.',
  image: 'https://via.placeholder.com/400x300/8B0000/FFFFFF?text=Tobacco+Crop',
  climate: 'Warm and dry (20°C - 30°C), requires dry weather at maturity.',
  soil: 'Light sandy loam to loamy soils with good drainage and low nitrogen.',
  sowingTime: 'Rabi (October-November)',
  harvestingTime: 'Rabi (February-March)',
  waterRequirements: 'Moderate, sensitive to waterlogging and excess moisture.',
  commonPests: 'Aphids, Whitefly, Tobacco Caterpillar.',
  commonDiseases: 'Leaf Curl Virus, Damping Off, Mosaic Virus.',
  yield: '1.5-2 tons/hectare of cured leaves.',
  cultivationPractices: [
    'Raising seedlings in nursery beds.',
    'Transplanting to main field after 30-40 days.',
    'Topping and sucker removal to improve leaf quality.',
    'Curing of leaves through air or flue curing.',
    'Grading and bundling for market.'
  ],
  fertilizerManagement: '60-80 kg Nitrogen, 40 kg Phosphorus, 40 kg Potassium per hectare. Excess nitrogen reduces leaf quality.',
  marketInfo: 'Regulated by Tobacco Board. Prices influenced by export demand and domestic consumption.'
},
{
  id: 22,
  name: 'Jute',
  scientificName: 'Corchorus olitorius / Corchorus capsularis',
  briefDescription: 'A fiber crop grown in humid regions, used for making sacks, ropes, and eco-friendly packaging.',
  fullDescription: 'Jute is a major fiber crop grown in the eastern states of India, especially West Bengal, Bihar, and Assam. It is known as the “Golden Fiber” and is used in making gunny bags, carpets, and biodegradable packaging. It thrives in warm, humid climates with plenty of rainfall.',
  image: 'https://via.placeholder.com/400x300/DAA520/000000?text=Jute+Crop',
  climate: 'Hot and humid (24°C - 35°C), requires high rainfall (150-200 cm).',
  soil: 'Alluvial soils rich in organic matter, with good water retention.',
  sowingTime: 'Kharif (March-May)',
  harvestingTime: 'Kharif (July-September)',
  waterRequirements: 'High, requires consistent moisture during growth.',
  commonPests: 'Stem Weevil, Hairy Caterpillar.',
  commonDiseases: 'Stem Rot, Anthracnose, Root Knot Nematode.',
  yield: '2-3 tons/hectare of fiber.',
  cultivationPractices: [
    'Broadcast or line sowing in well-prepared fields.',
    'Thinning and weeding for proper plant stand.',
    'Retting of harvested plants in water to extract fiber.',
    'Washing, drying, and bundling of fiber for sale.'
  ],
  fertilizerManagement: '40-60 kg Nitrogen, 30 kg Phosphorus, 20 kg Potassium per hectare.',
  marketInfo: 'High demand for eco-friendly packaging. Prices influenced by textile and export industries.'
},
{
  id: 23,
  name: 'Indigo',
  scientificName: 'Indigofera tinctoria',
  briefDescription: 'A traditional dye crop historically grown for its deep blue pigment, now cultivated on a smaller scale.',
  fullDescription: 'Indigo is a leguminous shrub historically cultivated in India for its natural blue dye, extracted from the leaves. Though synthetic dyes have largely replaced it, indigo is still grown in parts of Bihar, Tamil Nadu, and West Bengal for organic and artisanal dye markets. It also improves soil fertility through nitrogen fixation.',
  image: 'https://via.placeholder.com/400x300/191970/FFFFFF?text=Indigo+Crop',
  climate: 'Warm and humid (25°C - 35°C), prefers tropical to subtropical climates.',
  soil: 'Well-drained loamy soils with good organic matter.',
  sowingTime: 'Kharif (June-July)',
  harvestingTime: 'Multiple harvests possible; first cut after 3-4 months.',
  waterRequirements: 'Moderate, requires good moisture but not waterlogging.',
  commonPests: 'Leaf Hopper, Caterpillars.',
  commonDiseases: 'Leaf Spot, Root Rot.',
  yield: '2-3 tons/hectare of biomass; dye yield depends on processing.',
  cultivationPractices: [
    'Direct sowing or transplanting of seedlings.',
    'Regular weeding and pruning to encourage leaf growth.',
    'Harvesting leaves before flowering for best dye content.',
    'Fermentation and oxidation to extract indigo dye.'
  ],
  fertilizerManagement: '20-30 kg Nitrogen, 40 kg Phosphorus per hectare. Organic manure improves leaf yield.',
  marketInfo: 'Niche demand in organic textile and natural dye industries. Prices vary with artisanal and export markets.'
},
{
  id: 24,
  name: 'Tea',
  scientificName: 'Camellia sinensis',
  briefDescription: 'A major plantation crop grown in hilly regions, known for its aromatic leaves used in beverages.',
  fullDescription: 'Tea is a perennial plantation crop cultivated in the hilly regions of Assam, West Bengal (Darjeeling), Tamil Nadu, and Kerala. It requires a humid climate, well-distributed rainfall, and acidic soils. India is one of the largest producers and exporters of tea globally.',
  image: 'https://via.placeholder.com/400x300/006400/FFFFFF?text=Tea+Crop',
  climate: 'Cool and humid (20°C - 30°C), with 150-300 cm annual rainfall.',
  soil: 'Well-drained, deep, acidic loamy soils rich in organic matter.',
  sowingTime: 'Planting is done year-round in nurseries; field planting during monsoon.',
  harvestingTime: 'Plucking begins 3 years after planting and continues year-round.',
  waterRequirements: 'High, requires frequent rainfall or irrigation.',
  commonPests: 'Tea Mosquito Bug, Red Spider Mite, Thrips.',
  commonDiseases: 'Blister Blight, Root Rot, Dieback.',
  yield: '1.5-2.5 tons/hectare of made tea.',
  cultivationPractices: [
    'Propagation through cuttings or seeds.',
    'Shade management and pruning.',
    'Regular plucking of tender leaves.',
    'Irrigation and mulching in dry periods.',
    'Pest and disease control using IPM.'
  ],
  fertilizerManagement: 'Nitrogen-rich fertilizers (urea or ammonium sulfate), phosphorus, and potash applied in splits.',
  marketInfo: 'High domestic and export demand. Prices vary by quality, region, and global markets.'
},
{
  id: 25,
  name: 'Coffee',
  scientificName: 'Coffea arabica / Coffea canephora',
  briefDescription: 'A tropical plantation crop grown in shaded hilly areas, known for its beans used in beverages.',
  fullDescription: 'Coffee is grown in the hilly regions of Karnataka, Kerala, and Tamil Nadu. Arabica and Robusta are the two main varieties. It requires a warm, humid climate with shade and well-drained soils. India is a major exporter of coffee, especially Robusta.',
  image: 'https://via.placeholder.com/400x300/8B4513/FFFFFF?text=Coffee+Crop',
  climate: 'Warm and humid (15°C - 28°C), with 150-250 cm annual rainfall.',
  soil: 'Well-drained, deep, loamy soils rich in humus and slightly acidic.',
  sowingTime: 'Nursery sowing in June-July; transplanting after 6-8 months.',
  harvestingTime: 'Arabica: November-January; Robusta: December-February.',
  waterRequirements: 'Moderate to high, requires irrigation during dry spells.',
  commonPests: 'Coffee Borer, Mealybugs, White Stem Borer.',
  commonDiseases: 'Leaf Rust, Black Rot, Root Wilt.',
  yield: '0.8-1.2 tons/hectare for Arabica; 1.5-2 tons/hectare for Robusta.',
  cultivationPractices: [
    'Shade tree management and mulching.',
    'Timely pruning and desuckering.',
    'Irrigation during blossom and fruit setting.',
    'Manual harvesting of ripe berries.',
    'Processing via dry or wet methods.'
  ],
  fertilizerManagement: 'Balanced NPK with micronutrients like zinc and boron. Organic manure improves bean quality.',
  marketInfo: 'Export-oriented crop. Prices influenced by global coffee markets and quality grades.'
},
  {
    id: 26,
    name: 'Cotton',
    scientificName: 'Gossypium spp.',
    briefDescription: 'A crucial fiber crop and cash crop in India, thriving in tropical and subtropical climates, known for its white fluffy bolls.',
    fullDescription: 'Cotton is a major fiber crop cultivated during the Kharif season. It requires a uniform temperature of 21-30°C and 50-100 cm of rainfall. A sunny and dry period of about 200 frost-free days is essential during the flowering and boll development stages. Black cotton soils are ideal. Major producing states include Gujarat, Maharashtra, Telangana, and Karnataka.',
    image: 'https://via.placeholder.com/400x300/B8860B/FFFFFF?text=Cotton+Crop',
    climate: 'Tropical/subtropical (21-30°C), long frost-free period, sunny and dry at flowering.',
    soil: 'Black cotton soils (Regur soils), well-drained alluvial soils.',
    sowingTime: 'Kharif (April-July, depending on region and monsoon onset).',
    harvestingTime: 'Kharif (October-March, picking in stages).',
    waterRequirements: 'Moderate, sensitive to water logging. Needs intermittent dry spells.',
    commonPests: 'Pink Bollworm, American Bollworm, Whitefly, Jassids.',
    commonDiseases: 'Bacterial Blight, Verticillium Wilt, Alternaria Leaf Spot.',
    yield: 'Highly variable, 0.5-1.5 tons/hectare of lint for rainfed; 2-3 tons/hectare for irrigated hybrids.',
    cultivationPractices: [
      'Proper land preparation and deep ploughing.',
      'Sowing of Bt cotton hybrids for bollworm resistance.',
      'Nutrient management (N, P, K, Boron).',
      'Integrated Pest Management (IPM) with focus on bollworms and sucking pests.',
      'Defoliation before harvesting (if required).',
      'Manual picking of cotton bolls in stages.'
    ],
    fertilizerManagement: 'Requires high nitrogen, phosphorus, and potassium, plus micronutrients like boron and zinc.',
    marketInfo: 'Major cash crop, highly dependent on textile industry demand and global prices. MSP provided.'
  },
  {
    id: 27,
    name: 'Sugarcane',
    scientificName: 'Saccharum officinarum',
    briefDescription: 'A perennial grass grown for sugar production, important for the sugar and jaggery industry in India.',
    fullDescription: 'Sugarcane is a tropical crop that requires hot and humid climate with temperatures between 21-27°C and 75-150 cm of annual rainfall. It can grow on a variety of soils but thrives best on well-drained deep rich loamy soils. Uttar Pradesh, Maharashtra, Karnataka, and Tamil Nadu are major sugarcane producing states.',
    image: 'https://via.placeholder.com/400x300/556B2F/FFFFFF?text=Sugarcane+Crop',
    climate: 'Hot and humid (21-27°C), long growing season.',
    soil: 'Deep, rich, well-drained loamy soils.',
    sowingTime: 'Autumn (Oct-Nov), Spring (Feb-March), Adsali (July-August) in Maharashtra/Karnataka.',
    harvestingTime: '10-18 months after planting, depending on variety and season.',
    waterRequirements: 'Very high, 6-8 irrigations during dry periods. Can tolerate water stress better than waterlogging.',
    commonPests: 'Shoot Borer, Stalk Borer, Whitefly, Pyrilla.',
    commonDiseases: 'Red Rot, Smut, Wilt, Rust.',
    yield: 'Average 60-80 tons/hectare, 100+ tons/hectare in high-yielding regions.',
    cultivationPractices: [
      'Deep ploughing and thorough soil preparation.',
      'Planting of sett cuttings.',
      'Earthing up to prevent lodging.',
      'Detrashing to remove dry leaves.',
      'Balanced fertilization and timely irrigation.',
      'Integrated Pest and Disease Management.',
      'Harvesting by cutting canes close to the ground.'
    ],
    fertilizerManagement: 'Heavy feeder. Requires high doses of N, P, K, and micronutrients like Zinc, Iron.',
    marketInfo: 'Procured by sugar mills. Pricing controlled by government (SAP - State Advised Price, FRP - Fair and Remunerative Price).'
  },
  {
    id: 28,
    name: 'Potato',
    scientificName: 'Solanum tuberosum',
    briefDescription: 'A cool-season vegetable crop, widely consumed and grown in the plains during winter. Important for food security.',
    fullDescription: 'Potato is a cool-season crop, thriving in temperatures ranging from 15-20°C. It requires well-drained, sandy loam to silty loam soils. Frost-free conditions during tuberization are crucial. Uttar Pradesh, West Bengal, Bihar, and Punjab are major potato-producing states. It is a vital cash crop for many farmers.',
    image: 'https://via.placeholder.com/400x300/8B4513/FFFFFF?text=Potato+Crop',
    climate: 'Cool (15-20°C), sensitive to frost, especially during tuber development.',
    soil: 'Well-drained, fertile, sandy loam to silty loam soils with good organic matter.',
    sowingTime: 'Winter (October-November) in plains; Summer (March-April) in hills.',
    harvestingTime: 'Winter (January-March) in plains; Summer (July-August) in hills.',
    waterRequirements: 'Moderate to high, critical during tuber initiation and development.',
    commonPests: 'Aphids, Leaf Miners, Potato Tuber Moth.',
    commonDiseases: 'Late Blight, Early Blight, Common Scab, Brown Rot.',
    yield: 'Average 20-30 tons/hectare, 40+ tons/hectare for improved varieties under good management.',
    cultivationPractices: [
      'Selection of healthy, disease-free seed tubers.',
      'Proper land preparation and ridging.',
      'Balanced fertilization (N, P, K).',
      'Earthing up to protect tubers from light and pests.',
      'Timely irrigation and drainage.',
      'Integrated Pest and Disease Management.',
      'Harvesting when foliage dries, followed by proper curing and storage.'
    ],
    fertilizerManagement: 'Requires high Potassium and Phosphorus, along with Nitrogen. Often needs farmyard manure.',
    marketInfo: 'Highly volatile market prices. Demand is consistent. Important for processing industry (chips, fries).'
  },
  {
    id: 29,
    name: 'Tomato',
    scientificName: 'Solanum lycopersicum',
    briefDescription: 'A widely cultivated vegetable for fresh consumption and processing, adaptable to various climates.',
    fullDescription: 'Tomato is a warm-season crop, but it can be grown year-round in different parts of India depending on temperature and water availability. Ideal temperature for growth is 20-25°C. It requires well-drained, deep, and fertile loamy soils. Major producing states include Andhra Pradesh, Madhya Pradesh, Karnataka, and Odisha. It is a very popular cash crop for farmers.',
    image: 'https://via.placeholder.com/400x300/FF6347/FFFFFF?text=Tomato+Crop',
    climate: 'Warm (20-25°C), sensitive to frost and extreme heat.',
    soil: 'Well-drained sandy loam to clay loam soils with good organic content.',
    sowingTime: 'Kharif (June-July), Rabi (Oct-Nov), Summer (Feb-March).',
    harvestingTime: '70-100 days after transplanting, depending on variety and season.',
    waterRequirements: 'Moderate, consistent moisture crucial for fruit development.',
    commonPests: 'Fruit Borer, Whitefly, Leaf Miner, Thrips.',
    commonDiseases: 'Early Blight, Late Blight, Bacterial Wilt, Leaf Curl Virus, Tomato Mosaic Virus.',
    yield: 'Average 20-40 tons/hectare, 60+ tons/hectare for hybrids under protected cultivation.',
    cultivationPractices: [
      'Nursery raising and transplanting of healthy seedlings.',
      'Staking or trellising for support.',
      'Pruning and training (for indeterminate varieties).',
      'Balanced fertilization.',
      'Regular irrigation, especially during flowering and fruiting.',
      'Integrated Pest and Disease Management (IPM).',
      'Harvesting at appropriate maturity stage for fresh market or processing.'
    ],
    fertilizerManagement: 'Requires balanced NPK, with higher Potassium during fruiting. Calcium and Boron are also important.',
    marketInfo: 'High demand year-round. Prices are highly volatile, influenced by seasonal supply. Used fresh and for sauces, pastes.'
  },
  {
  id: 30,
  name: 'Rubber',
  scientificName: 'Hevea brasiliensis',
  briefDescription: 'A tropical plantation crop grown for latex, used in tires, footwear, and industrial products.',
  fullDescription: 'Rubber is a perennial plantation crop cultivated mainly in Kerala, Tamil Nadu, and Karnataka. It requires a hot, humid climate and well-distributed rainfall. Latex is extracted from the bark and processed into sheets or blocks for industrial use.',
  image: 'https://via.placeholder.com/400x300/2E8B57/FFFFFF?text=Rubber+Crop',
  climate: 'Hot and humid (25°C - 35°C), with 200-300 cm annual rainfall.',
  soil: 'Deep, well-drained lateritic or alluvial soils rich in organic matter.',
  sowingTime: 'Planting is done during monsoon (June-July).',
  harvestingTime: 'Latex tapping begins 5-7 years after planting and continues for 20-25 years.',
  waterRequirements: 'High, requires consistent moisture and no waterlogging.',
  commonPests: 'Scale Insects, Mites, Mealybugs.',
  commonDiseases: 'Leaf Fall Disease, Powdery Mildew, Root Rot.',
  yield: '1,500–2,000 kg/hectare of dry rubber annually.',
  cultivationPractices: [
    'Propagation through budded stumps or seedlings.',
    'Regular weeding and mulching.',
    'Tapping of latex using half-spiral cuts.',
    'Application of stimulants to enhance latex flow.',
    'Resting period for trees after tapping cycles.'
  ],
  fertilizerManagement: 'NPK (12:6:6) mixture applied in splits. Organic manure improves soil health.',
  marketInfo: 'Used in tire, footwear, and industrial sectors. Prices influenced by global rubber markets.'
},
{
  id: 31,
  name: 'Coconut',
  scientificName: 'Cocos nucifera',
  briefDescription: 'A tropical plantation crop grown for its nut, oil, water, and coir, often called the “Tree of Life.”',
  fullDescription: 'Coconut is a versatile crop grown in coastal regions of Kerala, Tamil Nadu, Karnataka, and Andhra Pradesh. It provides food, oil, fiber, and drinkable water. It thrives in warm, humid climates and is a key livelihood crop in coastal India.',
  image: 'https://via.placeholder.com/400x300/D2B48C/000000?text=Coconut+Crop',
  climate: 'Warm and humid (25°C - 32°C), with 100-200 cm annual rainfall.',
  soil: 'Well-drained sandy loam to lateritic soils with good water-holding capacity.',
  sowingTime: 'Year-round in well-irrigated areas; best during monsoon.',
  harvestingTime: 'First harvest after 5-7 years; continues for 60-80 years.',
  waterRequirements: 'High, especially during flowering and nut development.',
  commonPests: 'Rhinoceros Beetle, Red Palm Weevil, Mites.',
  commonDiseases: 'Bud Rot, Root Wilt, Stem Bleeding.',
  yield: '8,000–12,000 nuts/hectare/year under good management.',
  cultivationPractices: [
    'Planting of seedlings in pits with organic matter.',
    'Regular irrigation and mulching.',
    'Intercropping with spices or pulses.',
    'Timely pest and disease control.',
    'Harvesting mature nuts every 45-60 days.'
  ],
  fertilizerManagement: '20-30 kg FYM, 500 g Nitrogen, 320 g Phosphorus, 1,200 g Potassium per tree annually.',
  marketInfo: 'Used in oil, food, coir, and cosmetics. Prices vary with demand and export trends.'
},
{
  id: 32,
  name: 'Pearl Millet (Bajra)',
  scientificName: 'Pennisetum glaucum',
  briefDescription: 'A hardy millet grown in arid and semi-arid regions, known for its drought resistance.',
  fullDescription: 'Bajra is a staple millet crop grown in dry regions of India, especially Rajasthan, Gujarat, and Haryana. It is rich in nutrients and highly drought-tolerant, making it ideal for rainfed agriculture. It is used for food, fodder, and in traditional dishes.',
  image: 'https://via.placeholder.com/400x300/556B2F/FFFFFF?text=Bajra+Crop',
  climate: 'Hot and dry (25°C - 35°C), drought-tolerant.',
  soil: 'Light sandy to loamy soils, well-drained.',
  sowingTime: 'Kharif (June-July)',
  harvestingTime: 'Kharif (September-October)',
  waterRequirements: 'Low, suitable for rainfed conditions.',
  commonPests: 'Shoot Fly, Stem Borer, Aphids.',
  commonDiseases: 'Downy Mildew, Ergot, Smut.',
  yield: '1.5-2.5 tons/hectare; higher with hybrids.',
  cultivationPractices: [
    'Seed treatment and timely sowing.',
    'Thinning and gap filling for uniform stand.',
    'Weed control and timely irrigation (if needed).',
    'Use of resistant varieties.',
    'Harvesting at physiological maturity.'
  ],
  fertilizerManagement: '60-80 kg Nitrogen, 40 kg Phosphorus per hectare. Apply nitrogen in two splits.',
  marketInfo: 'High demand in dryland regions. Used in traditional foods and livestock feed.'
},
{
  id: 33,
  name: 'Arecanut',
  scientificName: 'Areca catechu',
  briefDescription: 'A tropical palm crop grown for its nuts, commonly used in chewing mixtures like pan and supari.',
  fullDescription: 'Arecanut is a perennial plantation crop cultivated mainly in Karnataka, Kerala, and Assam. The nuts are used in traditional chewing products and have cultural and religious significance in India. The crop thrives in warm, humid climates and requires well-distributed rainfall.',
  image: 'https://via.placeholder.com/400x300/A0522D/FFFFFF?text=Arecanut+Crop',
  climate: 'Warm and humid (20°C - 35°C), with 150-250 cm annual rainfall.',
  soil: 'Deep, well-drained loamy soils rich in organic matter.',
  sowingTime: 'Planting is done during monsoon (June-July).',
  harvestingTime: 'First harvest after 5-7 years; continues for 30-40 years.',
  waterRequirements: 'High, especially during dry spells; requires regular irrigation.',
  commonPests: 'Mites, Spindle Bug, Root Grub.',
  commonDiseases: 'Koleroga (Mahali), Yellow Leaf Disease, Anaberoga.',
  yield: '1,000–2,000 kg/hectare of dry nuts annually.',
  cultivationPractices: [
    'Propagation through seedlings or tissue culture.',
    'Regular irrigation and mulching.',
    'Intercropping with pepper or banana.',
    'Timely pest and disease control.',
    'Harvesting mature nuts every 45-60 days.'
  ],
  fertilizerManagement: '100 g Nitrogen, 40 g Phosphorus, 140 g Potassium per palm annually, split into 2-3 doses.',
  marketInfo: 'Used in chewing products and rituals. Prices vary with quality and regional demand.'
},
{
  id: 34,
  name: 'Turmeric',
  scientificName: 'Curcuma longa',
  briefDescription: 'A rhizomatous spice crop known for its golden color and medicinal properties, widely used in Indian cuisine and Ayurveda.',
  fullDescription: 'Turmeric is a tropical spice crop cultivated mainly in Andhra Pradesh, Tamil Nadu, Maharashtra, and Odisha. It is grown for its underground rhizomes, which are dried and ground into a bright yellow powder. Turmeric is used in cooking, cosmetics, and traditional medicine for its anti-inflammatory and antioxidant properties.',
  image: 'https://via.placeholder.com/400x300/FFD700/000000?text=Turmeric+Crop',
  climate: 'Warm and humid (20°C - 30°C), requires 100-200 cm rainfall.',
  soil: 'Well-drained loamy or alluvial soils rich in organic matter.',
  sowingTime: 'Kharif (May-June)',
  harvestingTime: '7-9 months after planting (January-March)',
  waterRequirements: 'Moderate to high, especially during rhizome development.',
  commonPests: 'Rhizome Fly, Shoot Borer, Scale Insects.',
  commonDiseases: 'Leaf Spot, Rhizome Rot, Leaf Blotch.',
  yield: '20-30 tons/hectare of fresh rhizomes.',
  cultivationPractices: [
    'Propagation through healthy rhizome pieces.',
    'Mulching and regular irrigation.',
    'Weed control and earthing up.',
    'Harvesting when leaves dry and rhizomes mature.',
    'Boiling, drying, and polishing of rhizomes.'
  ],
  fertilizerManagement: '20-30 tons FYM, 100 kg Nitrogen, 60 kg Phosphorus, 60 kg Potassium per hectare.',
  marketInfo: 'High demand in food, pharma, and cosmetic industries. Prices influenced by quality and curcumin content.'
},
{
  id: 35,
  name: 'Ginger',
  scientificName: 'Zingiber officinale',
  briefDescription: 'A pungent spice crop grown for its aromatic rhizomes, used in cooking, beverages, and traditional medicine.',
  fullDescription: 'Ginger is a tropical spice crop cultivated in Kerala, Karnataka, Meghalaya, and Sikkim. It is grown for its underground rhizomes, which are used fresh, dried, or processed into powder and oil. Ginger is valued for its flavor, digestive properties, and medicinal uses.',
  image: 'https://via.placeholder.com/400x300/DEB887/000000?text=Ginger+Crop',
  climate: 'Warm and humid (20°C - 30°C), with 150-300 cm rainfall.',
  soil: 'Well-drained loamy soils rich in humus and organic matter.',
  sowingTime: 'Kharif (April-May)',
  harvestingTime: '8-10 months after planting (December-February)',
  waterRequirements: 'High, especially during early growth and rhizome formation.',
  commonPests: 'Shoot Borer, Rhizome Scale, Nematodes.',
  commonDiseases: 'Soft Rot, Leaf Spot, Bacterial Wilt.',
  yield: '15-25 tons/hectare of fresh rhizomes.',
  cultivationPractices: [
    'Propagation through seed rhizomes.',
    'Mulching and regular irrigation.',
    'Weed control and earthing up.',
    'Harvesting when leaves yellow and rhizomes mature.',
    'Cleaning, drying, and curing of rhizomes.'
  ],
  fertilizerManagement: '25 tons FYM, 75 kg Nitrogen, 50 kg Phosphorus, 50 kg Potassium per hectare.',
  marketInfo: 'Used in food, beverages, and herbal medicine. Prices vary with quality and export demand.'
},
 {
    id: 36,
    name: 'Maize (Corn)',
    scientificName: 'Zea mays',
    briefDescription: 'A versatile crop used for food, feed, and industrial purposes. Grown in both Kharif and Rabi seasons in various parts of India.',
    fullDescription: 'Maize is a crop that thrives under a wide range of climatic conditions. It requires temperatures between 21-27°C and can grow in regions with 50-100 cm rainfall. It is significant as a coarse cereal, fodder, and raw material for industrial products like starch, oil, and alcoholic beverages. Karnataka, Andhra Pradesh, Uttar Pradesh, and Bihar are major producers.',
    image: 'https://via.placeholder.com/400x300/DAA520/FFFFFF?text=Maize+Crop',
    climate: 'Warm and moist (21-27°C), sensitive to frost.',
    soil: 'Deep, fertile, well-drained loamy to heavy clayey soils.',
    sowingTime: 'Kharif (June-July), Rabi (October-November in South/East India), Zaid (Feb-March).',
    harvestingTime: 'Kharif (September-October), Rabi (March-April), Zaid (May-June).',
    waterRequirements: 'Moderate to high, critical at silking and tasseling stages.',
    commonPests: 'Stem Borer, Fall Armyworm, Aphids.',
    commonDiseases: 'Downy Mildew, Rust, Stalk Rot.',
    yield: 'Average 2-4 tons/hectare, 6-8 tons/hectare for hybrid varieties under optimal conditions.',
    cultivationPractices: [
      'Proper seedbed preparation.',
      'Timely sowing of improved varieties/hybrids.',
      'Optimum plant spacing and population.',
      'Balanced fertilization (N, P, K, Zn).',
      'Efficient weed management (manual or chemical).',
      'Integrated Pest Management (IPM) for Fall Armyworm.',
      'Harvesting at physiological maturity.'
    ],
    fertilizerManagement: 'High nitrogen demand (120-150 kg/ha), adequate Phosphorus (60 kg/ha) and Potassium (40 kg/ha). Zinc is often crucial.',
    marketInfo: 'Growing demand as poultry feed and industrial raw material. Subject to market price fluctuations, but rising consumption. MSP is also provided.'
  },
{
  id: 37,
  name: 'Garlic',
  scientificName: 'Allium sativum',
  briefDescription: 'A pungent spice crop grown for its bulbs, widely used in cooking and traditional medicine.',
  fullDescription: 'Garlic is a cool-season spice crop cultivated in Madhya Pradesh, Gujarat, Rajasthan, and Uttar Pradesh. It is grown for its underground bulbs, which are used in culinary dishes, pickles, and Ayurvedic medicine. Garlic is known for its antimicrobial and heart-health benefits.',
  image: 'https://via.placeholder.com/400x300/F5F5DC/000000?text=Garlic+Crop',
  climate: 'Cool and dry (12°C - 25°C), frost-sensitive.',
  soil: 'Well-drained loamy soils rich in organic matter.',
  sowingTime: 'Rabi (October-November)',
  harvestingTime: 'Rabi (March-April)',
  waterRequirements: 'Moderate, 4-5 irrigations depending on rainfall.',
  commonPests: 'Thrips, Onion Maggot, Nematodes.',
  commonDiseases: 'White Rot, Downy Mildew, Purple Blotch.',
  yield: '5-8 tons/hectare of bulbs.',
  cultivationPractices: [
    'Propagation through cloves.',
    'Timely sowing and spacing.',
    'Regular weeding and irrigation.',
    'Harvesting when leaves turn yellow and dry.',
    'Curing and storage of bulbs.'
  ],
  fertilizerManagement: '100 kg Nitrogen, 50 kg Phosphorus, 50 kg Potassium per hectare.',
  marketInfo: 'High demand in culinary and medicinal markets. Prices vary with quality and storage.'
},
{
  id: 38,
  name: 'Cardamom',
  scientificName: 'Elettaria cardamomum',
  briefDescription: 'A high-value spice crop known as the “Queen of Spices,” grown in shaded, humid forests.',
  fullDescription: 'Cardamom is a perennial spice crop cultivated in the Western Ghats of Kerala, Karnataka, and Tamil Nadu. It thrives under forest canopy with high humidity and is used in sweets, teas, and perfumes. India is one of the largest producers and exporters of cardamom.',
  image: 'https://via.placeholder.com/400x300/556B2F/FFFFFF?text=Cardamom+Crop',
  climate: 'Cool and humid (15°C - 30°C), with 150-300 cm rainfall.',
  soil: 'Well-drained forest loam soils rich in organic matter.',
  sowingTime: 'Nursery sowing in March-April; transplanting in June-July.',
  harvestingTime: 'October to February, depending on region.',
  waterRequirements: 'High, requires frequent rainfall or irrigation.',
  commonPests: 'Thrips, Borers, Root Grubs.',
  commonDiseases: 'Katte Disease, Rhizome Rot, Leaf Blight.',
  yield: '150-300 kg/hectare of dry capsules.',
  cultivationPractices: [
    'Shade management and mulching.',
    'Regular weeding and irrigation.',
    'Hand harvesting of mature capsules.',
    'Drying and grading for market.'
  ],
  fertilizerManagement: '75 kg Nitrogen, 75 kg Phosphorus, 150 kg Potassium per hectare, split into 3-4 doses.',
  marketInfo: 'High export value. Prices influenced by quality, aroma, and global demand.'
},
{
  id: 39,
  name: 'Black Pepper',
  scientificName: 'Piper nigrum',
  briefDescription: 'A perennial climbing vine known as the “King of Spices,” grown for its pungent berries.',
  fullDescription: 'Black pepper is a tropical spice crop cultivated mainly in Kerala, Karnataka, and Tamil Nadu. It grows as a climber on support trees and is harvested for its unripe green berries, which are dried to produce black pepper. It is widely used in cooking and traditional medicine.',
  image: 'https://via.placeholder.com/400x300/000000/FFFFFF?text=Black+Pepper+Crop',
  climate: 'Hot and humid (20°C - 35°C), with 150-300 cm rainfall.',
  soil: 'Well-drained lateritic or forest loam soils rich in organic matter.',
  sowingTime: 'Planting during monsoon (June-July).',
  harvestingTime: 'December to March, depending on region.',
  waterRequirements: 'High, requires frequent rainfall or irrigation.',
  commonPests: 'Pollu Beetle, Top Shoot Borer, Scale Insects.',
  commonDiseases: 'Quick Wilt, Foot Rot, Leaf Spot.',
  yield: '1-2 tons/hectare of dry pepper under good management.',
  cultivationPractices: [
    'Propagation through rooted cuttings.',
    'Training vines on support trees or poles.',
    'Regular mulching and shade management.',
    'Harvesting when berries turn red; drying for black pepper.',
    'Pest and disease control using IPM.'
  ],
  fertilizerManagement: '100 kg Nitrogen, 40 kg Phosphorus, 140 kg Potassium per hectare, split into 2-3 doses.',
  marketInfo: 'High export value. Prices influenced by global spice markets and quality.'
},
{
  id: 40,
  name: 'Coriander',
  scientificName: 'Coriandrum sativum',
  briefDescription: 'An annual herb grown for its aromatic leaves and seeds, widely used in Indian cooking.',
  fullDescription: 'Coriander is a cool-season spice crop cultivated in Rajasthan, Madhya Pradesh, Gujarat, and Andhra Pradesh. Both its fresh leaves (cilantro) and dried seeds are used in culinary dishes. It is also valued for its digestive and medicinal properties.',
  image: 'https://via.placeholder.com/400x300/228B22/FFFFFF?text=Coriander+Crop',
  climate: 'Cool and dry (15°C - 25°C), frost-sensitive.',
  soil: 'Well-drained loamy soils with good fertility.',
  sowingTime: 'Rabi (October-November)',
  harvestingTime: 'Rabi (February-March)',
  waterRequirements: 'Low to moderate, 2-3 irrigations depending on rainfall.',
  commonPests: 'Aphids, Cutworms, Thrips.',
  commonDiseases: 'Powdery Mildew, Stem Gall, Wilt.',
  yield: '0.8-1.5 tons/hectare of seeds.',
  cultivationPractices: [
    'Direct sowing with proper spacing.',
    'Weed control and light irrigation.',
    'Harvesting when seeds turn brown and dry.',
    'Drying and threshing for seed extraction.'
  ],
  fertilizerManagement: '40 kg Nitrogen, 30 kg Phosphorus per hectare.',
  marketInfo: 'Used in spice blends and condiments. Prices vary with quality and seasonal demand.'
},
{
  id: 41,
  name: 'Cumin',
  scientificName: 'Cuminum cyminum',
  briefDescription: 'A Rabi spice crop grown for its aromatic seeds, widely used in Indian cooking and spice blends.',
  fullDescription: 'Cumin is a cool-season spice crop cultivated mainly in Rajasthan and Gujarat. The seeds are used whole or ground in curries, spice mixes, and traditional medicine. It thrives in dry climates and is sensitive to frost and waterlogging.',
  image: 'https://via.placeholder.com/400x300/D2B48C/000000?text=Cumin+Crop',
  climate: 'Cool and dry (15°C - 25°C), frost-sensitive.',
  soil: 'Well-drained sandy loam to loamy soils with low moisture.',
  sowingTime: 'Rabi (November-December)',
  harvestingTime: 'Rabi (March-April)',
  waterRequirements: 'Low, 1-2 light irrigations if needed.',
  commonPests: 'Aphids, Thrips, Cutworms.',
  commonDiseases: 'Powdery Mildew, Wilt, Blight.',
  yield: '0.6-1.2 tons/hectare of seeds.',
  cultivationPractices: [
    'Direct sowing with proper spacing.',
    'Timely weeding and pest monitoring.',
    'Harvesting when umbels turn brown and dry.',
    'Drying and threshing for seed extraction.'
  ],
  fertilizerManagement: '30-40 kg Nitrogen, 20-30 kg Phosphorus per hectare.',
  marketInfo: 'Used in spice blends and exports. Prices influenced by quality and global demand.'
},
{
  id: 42,
  name: 'Fenugreek (Methi)',
  scientificName: 'Trigonella foenum-graecum',
  briefDescription: 'A leafy spice and medicinal herb grown for its seeds and tender leaves, used in cooking and Ayurveda.',
  fullDescription: 'Fenugreek is a Rabi season crop cultivated in Rajasthan, Gujarat, Madhya Pradesh, and Uttar Pradesh. Its seeds are used in pickles and spice blends, while the leaves are consumed as a leafy vegetable. It is also valued for its medicinal properties, especially for digestion and diabetes management.',
  image: 'https://via.placeholder.com/400x300/9ACD32/000000?text=Fenugreek+Crop',
  climate: 'Cool and dry (10°C - 25°C), frost-sensitive.',
  soil: 'Well-drained loamy soils rich in organic matter.',
  sowingTime: 'Rabi (October-November)',
  harvestingTime: 'Leaves: 30-40 days after sowing; Seeds: February-March',
  waterRequirements: 'Low to moderate, 2-3 irrigations depending on rainfall.',
  commonPests: 'Aphids, Cutworms, Leaf Miners.',
  commonDiseases: 'Powdery Mildew, Root Rot, Downy Mildew.',
  yield: '0.8-1.2 tons/hectare of seeds; 10-15 tons/hectare of fresh leaves.',
  cultivationPractices: [
    'Direct sowing with proper spacing.',
    'Thinning and weeding after germination.',
    'Harvesting leaves periodically or seeds at maturity.',
    'Drying and threshing for seed collection.'
  ],
  fertilizerManagement: '20-30 kg Nitrogen, 40 kg Phosphorus per hectare.',
  marketInfo: 'Used in food, herbal medicine, and exports. Prices vary with season and quality.'
}
  // Add more crops here following the same structure
];